//! Registry manifest (`.upskill-registry.json`, `schema: 1`) and
//! `REGISTRY.md` identity.
//!
//! Per ADR-0007. The manifest mirrors `crate::lockfile`: a `schema: 1`
//! JSON document with `load`/`save` and newer-schema rejection. It is
//! generated by `upskill registry build` from `REGISTRY.md` frontmatter
//! plus a tree scan, and fetched verbatim by consumers.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// On-disk manifest filename (registry repo root).
pub const MANIFEST_NAME: &str = ".upskill-registry.json";
/// Authored identity filename (registry repo root).
pub const REGISTRY_MD: &str = "REGISTRY.md";
/// Schema version this module produces.
pub const CURRENT_SCHEMA: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RegistryManifest {
    pub schema: u32,
    pub registry: RegistryIdentity,
    #[serde(default)]
    pub items: Vec<ManifestItem>,
    #[serde(default)]
    pub bundles: Vec<ManifestBundle>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RegistryIdentity {
    pub name: String,
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maintainer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct ManifestItem {
    pub name: String,
    /// `rule` | `skill` | `agent`.
    pub kind: String,
    /// Repo-root-relative directory of the item.
    pub path: String,
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct ManifestBundle {
    pub name: String,
    pub description: String,
    /// Repo-root-relative path to the `*.bundle.md` file.
    pub path: String,
}

/// Parsed `REGISTRY.md` frontmatter. `schema` reuses the item
/// `SchemaVersion` newtype so a future schema is rejected on parse.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
pub struct RegistryMeta {
    pub schema: crate::model::SchemaVersion,
    pub name: String,
    pub description: String,
    pub maintainer: Option<String>,
    pub homepage: Option<String>,
}

impl RegistryManifest {
    /// Load `<root>/.upskill-registry.json`. Errors when the file is
    /// absent (callers decide whether that is fatal), unparseable, or
    /// carries a schema newer than `CURRENT_SCHEMA`.
    pub fn load(root: &Path) -> Result<Self> {
        let path = manifest_path(root);
        let raw =
            std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
        let parsed: Self =
            serde_json::from_str(&raw).with_context(|| format!("parse {}", path.display()))?;
        if parsed.schema > CURRENT_SCHEMA {
            anyhow::bail!(
                "{}: schema {} is newer than this implementation supports \
                 (max {}); upgrade upskill",
                path.display(),
                parsed.schema,
                CURRENT_SCHEMA
            );
        }
        if parsed.schema != CURRENT_SCHEMA {
            anyhow::bail!(
                "{}: unsupported schema {} (expected {})",
                path.display(),
                parsed.schema,
                CURRENT_SCHEMA
            );
        }
        Ok(parsed)
    }

    /// Serialize to deterministic pretty JSON with a trailing newline.
    pub fn to_pretty_json(&self) -> Result<String> {
        let json = serde_json::to_string_pretty(self).context("serialize manifest")?;
        Ok(format!("{json}\n"))
    }

    /// Persist to `<root>/.upskill-registry.json`.
    pub fn save(&self, root: &Path) -> Result<()> {
        let path = manifest_path(root);
        std::fs::write(&path, self.to_pretty_json()?)
            .with_context(|| format!("write {}", path.display()))
    }
}

fn manifest_path(root: &Path) -> PathBuf {
    root.join(MANIFEST_NAME)
}

/// Minimal frontmatter shared by every entrypoint kind. `name` and
/// `description` are common §3.1 fields; `metadata.version` is optional.
#[derive(Deserialize)]
struct EntrypointMeta {
    name: String,
    description: String,
    #[serde(default)]
    metadata: Option<crate::model::Metadata>,
}

/// Walk `root` one level deep for `RULE/SKILL/AGENT.md` entrypoints and
/// recurse for `*.bundle.md`. Returns `(items, bundles)`, each sorted
/// for deterministic manifest output. Hidden directories are skipped.
pub fn scan(root: &Path) -> Result<(Vec<ManifestItem>, Vec<ManifestBundle>)> {
    let mut items = Vec::new();
    for entry in std::fs::read_dir(root)
        .with_context(|| format!("read {}", root.display()))?
        .flatten()
    {
        let dir = entry.path();
        if !dir.is_dir() {
            continue;
        }
        let dir_name = dir.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if dir_name.starts_with('.') {
            continue;
        }
        for (file, kind) in [
            ("RULE.md", "rule"),
            ("SKILL.md", "skill"),
            ("AGENT.md", "agent"),
        ] {
            let entry_path = dir.join(file);
            if !entry_path.is_file() {
                continue;
            }
            let raw = std::fs::read_to_string(&entry_path)
                .with_context(|| format!("read {}", entry_path.display()))?;
            let (meta, _body): (EntrypointMeta, &str) = crate::parse::frontmatter::parse(&raw)
                .with_context(|| format!("parse {}", entry_path.display()))?;
            items.push(ManifestItem {
                name: meta.name,
                kind: kind.to_string(),
                path: dir_name.to_string(),
                description: meta.description,
                version: meta.metadata.and_then(|m| m.version),
            });
        }
    }

    let mut bundles = Vec::new();
    scan_bundles(root, root, &mut bundles)?;

    items.sort();
    bundles.sort();
    Ok((items, bundles))
}

fn scan_bundles(root: &Path, dir: &Path, out: &mut Vec<ManifestBundle>) -> Result<()> {
    for entry in std::fs::read_dir(dir)
        .with_context(|| format!("read {}", dir.display()))?
        .flatten()
    {
        let path = entry.path();
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if name_str.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            scan_bundles(root, &path, out)?;
        } else if path.is_file() && name_str.ends_with(".bundle.md") {
            let raw = std::fs::read_to_string(&path)
                .with_context(|| format!("read {}", path.display()))?;
            let (meta, _body): (EntrypointMeta, &str) = crate::parse::frontmatter::parse(&raw)
                .with_context(|| format!("parse {}", path.display()))?;
            let rel = path
                .strip_prefix(root)
                .unwrap_or(&path)
                .to_string_lossy()
                .replace('\\', "/");
            out.push(ManifestBundle {
                name: meta.name,
                description: meta.description,
                path: rel,
            });
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest() -> RegistryManifest {
        RegistryManifest {
            schema: CURRENT_SCHEMA,
            registry: RegistryIdentity {
                name: "platform-registry".into(),
                description: "Baseline content".into(),
                maintainer: Some("platform-dx".into()),
                homepage: None,
            },
            items: vec![ManifestItem {
                name: "license-awareness".into(),
                kind: "rule".into(),
                path: "license-awareness".into(),
                description: "Flag unlicensed external code".into(),
                version: Some("1.2.0".into()),
            }],
            bundles: vec![],
        }
    }

    #[test]
    fn save_and_load_roundtrip() {
        let tmp = tempfile::tempdir().unwrap();
        let m = manifest();
        m.save(tmp.path()).expect("save");
        let loaded = RegistryManifest::load(tmp.path()).expect("load");
        assert_eq!(loaded, m);
    }

    #[test]
    fn pretty_json_has_trailing_newline() {
        assert!(manifest().to_pretty_json().unwrap().ends_with("}\n"));
    }

    #[test]
    fn load_rejects_newer_schema() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join(MANIFEST_NAME),
            r#"{"schema":99,"registry":{"name":"x","description":"y"},"items":[],"bundles":[]}"#,
        )
        .unwrap();
        let err = RegistryManifest::load(tmp.path()).expect_err("must reject");
        assert!(err.to_string().contains("schema 99"));
    }

    #[test]
    fn registry_meta_rejects_schema_2() {
        let yaml = "schema: 2\nname: x\ndescription: y\n";
        let err = serde_yaml_ng::from_str::<RegistryMeta>(yaml).expect_err("must reject");
        assert!(err.to_string().contains("schema version 2"));
    }

    #[test]
    fn scan_collects_items_and_bundles_sorted() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        std::fs::create_dir(root.join("zeta")).unwrap();
        std::fs::write(
            root.join("zeta/SKILL.md"),
            "---\nschema: 1\nname: zeta\ndescription: a skill\nmetadata:\n  version: \"1.0.0\"\n---\nbody\n",
        )
        .unwrap();
        std::fs::create_dir(root.join("alpha")).unwrap();
        std::fs::write(
            root.join("alpha/RULE.md"),
            "---\nschema: 1\nname: alpha\ndescription: a rule\n---\nbody\n",
        )
        .unwrap();
        std::fs::write(
            root.join("base.bundle.md"),
            "---\nschema: 1\nname: base\ndescription: a bundle\nitems: {}\n---\nbody\n",
        )
        .unwrap();

        let (items, bundles) = scan(root).expect("scan");

        assert_eq!(items.len(), 2);
        assert_eq!(items[0].name, "alpha"); // sorted
        assert_eq!(items[0].kind, "rule");
        assert_eq!(items[0].path, "alpha");
        assert_eq!(items[0].version, None);
        assert_eq!(items[1].name, "zeta");
        assert_eq!(items[1].kind, "skill");
        assert_eq!(items[1].version.as_deref(), Some("1.0.0"));
        assert_eq!(bundles.len(), 1);
        assert_eq!(bundles[0].name, "base");
        assert_eq!(bundles[0].path, "base.bundle.md");
    }
}
